### ISSUE TITLE
Bogus example in comment/README.md

### ISSUE THREAD

**Issue by skx** [yahoo/vssh#1]
The README.md file, and the vssh.go docstring [available here](https://github.com/yahoo/vssh/blob/460d59466777798a09df1dec53543a508e4e9050/vssh.go#L306) both contain the following example:

> vs.RunWithLabel(ctx, cmd, timeout, "POP == LAX || POP == DCA) && OS == JUNOS")

The expression there is malformed:

> POP == LAX || POP == DCA) && OS == JUNOS

Notice the closing `)`, without an opening `(`.

**Comment by mehrdadrad** [comment]
@skx thanks! just fixed
