### ISSUE TITLE
SetInitNumProc compile error

### ISSUE THREAD

**Issue by jvijay-work** [yahoo/vssh#2]
With the following code
```
        vs := vssh.New()
        vs.SetInitNumProc(2)
        vs.Start()
```

I am getting the following output
command-line-arguments
./main.go:13:4: vs.SetInitNumProc undefined (type *vssh.VSSH has no field or method SetInitNumProc)

**Comment by mehrdadrad** [comment]
Thanks for reporting this issue.
It fixed. pls update the library then try again and let me know if you still has issue.
